feat: import-export type and atom
codelab-ai/web pull request #1530
Opened 2022-04-06 15:14 UTC by antonmihaylov

fixes #1523 #1532

2022-04-08 21:10 UTC, webberwang requested changes

2022-04-08 21:10 UTC, webberwang commented on apps/web/src/graphql/repositories/admin/exportAdminData.cypher
> +                apoc.map.merge(properties(rel), { source: startNode(rel).id, target: endNode(rel).id, __resolveType: 'Field'})],
Actually thinking of changing this graph structure to using descendent id approach, so we don't need to have a complicated cypher query like this

2022-04-08 21:10 UTC, webberwang commented on libs/frontend/modules/type/src/store/type-import.service.ts
> +  private makeCreateInput(
I would assume these can be re-used for normal type create? We could have a shared TypeInputFactory?

2022-04-09 07:58 UTC, antonmihaylov commented on apps/web/src/graphql/repositories/admin/exportAdminData.cypher
> +                apoc.map.merge(properties(rel), { source: startNode(rel).id, target: endNode(rel).id, __resolveType: 'Field'})],
I didn't use this at all, only regular generated graphql endpoints. I.e. the descendantIds approach

2022-04-09 08:02 UTC, antonmihaylov commented on libs/frontend/modules/type/src/store/type-import.service.ts
> +  private makeCreateInput(
Good idea!

2022-04-09 09:34 UTC, webberwang commented on apps/web/src/graphql/repositories/admin/exportAdminData.cypher
> +                apoc.map.merge(properties(rel), { source: startNode(rel).id, target: endNode(rel).id, __resolveType: 'Field'})],
yeah let's remove it

2022-04-12 02:15 UTC, merged