1617 custom domains 2
codelab-ai/web pull request #1628
Opened 2022-06-23 05:57 UTC by phmngocnghia

## Description (Optional)

## Related Issue(s)

Fixes #

2022-07-02 09:29 UTC, antonmihaylov commented on libs/backend/src/schema/schema.ts
> +  return `${parent.name.toLowerCase()}`
Use something like https://www.npmjs.com/package/slugify toLowerCase doesn't produce valid url slugs

2022-07-02 09:29 UTC, antonmihaylov commented on apps/web/pages/_sites/user/[user]/[app]/[page]/index.tsx
> +  return {
This doesn't seem functional, but I suppose it will be in another PR, right?

2022-07-06 01:41 UTC, webberwang commented on schema.api.graphql
> +  domains: [String!]!
Wouldn't an app only have 1 domain?

2022-07-22 08:25 UTC, antonmihaylov commented on apps/web/pages/_sites/user/[user]/[app]/[page]/index.tsx
> +      const [page] = await pageService.getAll({
Can we avoid fetching anything on the client side at all? I imagine we can move all of this in getStaticProps and pass it down as props to the page

2022-07-25 21:53 UTC, webberwang requested changes
I took a quick look some minor things

2022-07-25 21:53 UTC, webberwang commented on libs/frontend/modules/app/src/store/app.service.ts
> +    this.apps.set(app.id, appModel as any)
how come cast is needed here?

2022-07-25 21:53 UTC, webberwang commented on libs/frontend/modules/app/src/use-cases/get-apps/ItemDropdown.tsx
> +  const onEditClick = () => appService.updateModal.open(appRef(app.id) as any)
Also here

2022-07-25 21:53 UTC, webberwang commented on libs/frontend/modules/domain/src/use-cases/create-domain/CreateDomainModal.tsx
> +    return domainService.create(data as any)
also here

2022-07-25 21:53 UTC, webberwang commented on libs/frontend/modules/domain/src/use-cases/get-domain/GetDomainsItem/GetDomainsItem.tsx
> +    const url = `https://${domain.name.replace('https://', '')}`
I think better to convert to `new URL()` object then access the parts you need

2022-07-26 04:21 UTC, phmngocnghia commented on libs/frontend/modules/domain/src/use-cases/get-domain/GetDomainsItem/GetDomainsItem.tsx
> +    const url = `https://${domain.name.replace('https://', '')}`
@webberwang the domain name is raw. I'm going to validate them using https://www.npmjs.com/package/is-valid-domain
I think we should expect the domain is loaded with `https` protocol

2022-07-26 07:54 UTC, antonmihaylov requested changes
Again, massive work, just small comments

2022-07-26 07:54 UTC, antonmihaylov commented on apps/cli/src/repository/app.repo.ts
> +        slug: app.name,
Is this right, shouldn't it be app.slug?

2022-07-26 07:54 UTC, antonmihaylov commented on apps/web/pages/_middleware.ts
> +  const matchedVercelDomain = hostname?.includes(vercelURL)
String(undefined) produces 'undefined', so this will actually match if the hostname for some reason includes the word undefined

2022-07-26 07:54 UTC, antonmihaylov commented on apps/web/pages/_middleware.ts
> +  const isRootHostName = Boolean(matchedPublicDomains)
Is there a reason to use .find and Boolean instead of .some()?

2022-07-26 13:46 UTC, phmngocnghia commented on libs/backend/src/schema/schema.ts
> +  return `${parent.name.toLowerCase()}`
I removed this. The slugs can be inputted on the modal when creating/updating the domain name. The input will be slugified using `slugify`

2022-07-28 07:37 UTC, merged