Component tree collapse fix
codelab-ai/web pull request #1639
Opened 2022-07-10 08:34 UTC by mohasarc

## Description (Optional)
Fixes the issue of selecting an element from a different component causes the component tree to collapse. (6) from the list in #1630.

To fix the issue I added a custom hook to preserve BuilderTree expanded node ids because the list is lost when the BuilderTree is rerendered. BuilderTree rerenders when the activeComponent changes.

## Related Issue(s)
Related: #1630

2022-07-11 15:18 UTC, antonmihaylov commented
This seems a bit like a hack and could lead to other bugs down the line.
Would it be possible to have a better solution if we keep the expanded ids in the mobx state?

2022-07-11 19:38 UTC, mohasarc commented
> This seems a bit like a hack and could lead to other bugs down the line. Would it be possible to have a better solution if we keep the expanded ids in the mobx state?

Yeah that make sense. The reason I didn't wanna use mobx is that it is not used anywhere else in the application.

2022-07-11 19:47 UTC, antonmihaylov commented
True, bit we need it to persist between full rerenders so I think it's a good use case

2022-07-15 21:56 UTC, antonmihaylov requested changes

2022-07-16 09:02 UTC, mohasarc commented on libs/frontend/modules/builder/src/hooks/useExpandedNodes.tsx
> +const builderTreeModel = new BuilderTreeModel({ expandedNodeIds: [] })
That make sense, thanks for the feedback. I implemented it as you described.

2022-07-20 10:55 UTC, merged